apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

nameSuffix: -qas

namespace: charlie-qas

commonAnnotations:
  Projeto: Charlie-qas

patches:
- path: env-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: charlie-server-deploy
 
images:
- name: acrcharliehypera.azurecr.io/charlie-server
  newTag: 1.0.0-1401-qas
