apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

nameSuffix: -prd

namespace: charlie-prd

commonAnnotations:
  Projeto: Charlie-prd

images:
- name: acrcharliehypera.azurecr.io/charlie-server
  newTag: 1.0.0-1369-prd
