apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prd
namespace: charlie-prd

resources:
  - ../../base
  - ns.yaml

commonAnnotations:
  Projeto: Charlie-prd

images:
- name: acrcharliehypera.azurecr.io/charlie-server
  newTag: 1.0.0-1368-prd
