apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -dev

namespace: charlie-dev

commonAnnotations:
  Projeto: Charlie

images:
- name: acrcharliehypera.azurecr.io/charlie-server
  newTag: ca36178c4fada61b880f7dba6597d3ca9446b09e-dev
