apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -dev

namespace: charlie-dev

commonAnnotations:
  Projeto: Charlie

images:
- name: acrcharliehypera.azurecr.io/charlie-server
  newTag: 22c8cb91871f78bd5bab4d3c63175287d5001d38-dev
