apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

namespace: charlie-dev

resources:
- ../../base

commonAnnotations:
  Projeto: Charlie-dev

images:
- name: acrcharliehypera.azurecr.io/charlie-server
  newTag: 1.0.0-1368-dev
